"""Create emergency_cases table

Revision ID: 30c1d4691195
Revises: e974a5820bfe
Create Date: 2025-11-19 16:40:41.799700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30c1d4691195'
down_revision: Union[str, Sequence[str], None] = 'e974a5820bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_cases')
    # ### end Alembic commands ###
